spring.application.name=BrainConnect
spring.datasource.url=jdbc:mysql://localhost:3306/brainconnect
spring.datasource.username=root
spring.datasource.password=
spring.jpa.show-sql=true
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.thymeleaf.cache=false
logging.level.org.thymeleaf=DEBUG
spring.main.allow-circular-references=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
server.port=8080